spring:
  application:
    name: homepage-zuul
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/
zuul:
  prefix: /tuyrk
  routes:
    course:
      path: /homepage-course/**
      serviceId: eureka-client-homepage-course
      strip-prefix: false
    user:
      path: /homepage-user/**
      serviceId: eureka-client-homepage-user
      strip-prefix: false
