spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/coding_117_wx_sell?serverTimezone=GMT%2b8&characterEncoding=utf8&useSSL=false #
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
    password:
server:
  servlet:
    context-path: /sell
  port: 8090

wechat:
  mpAppId: wxe6a4566e548b4772
  mpAppSecret: 9c75c3368067822fa8fe76c28875aff3
  openAppId: 123
  openAppSecret: 123
  payMpAppId: 123
  payMchId: 123
  payMchKey: 123
  payKeyPath: 123
  payNotifyUrl: http://tyk.nat300.top/sell/pay/notify
  templateId:
    orderStatus: 8C7fzoKYap778H015J8zPAtkvMPRNkKn088RNgGeb2k

project-url:
  wechatMpAuthorize: http://tyk.nat300.top
  wechatOpenAuthorize: http://tyk.nat300.top
  sell: http://tyk.nat300.top
mybatis:
  mapper-locations: classpath:mapper/*.xml
